version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: ironlogic-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ironlogic
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - ironlogic-network

  # Optional: MongoDB Express (web-based admin interface)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: ironlogic-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - ironlogic-network

volumes:
  mongodb_data:
    driver: local

networks:
  ironlogic-network:
    driver: bridge 